"""
Evil Hunter 配置
"""
from typing import List

# Hunter Box Coordinates
FIRST_X = 70.0
SECOND_X = 250.0
THIRD_X = 430.0
FOURTH_X = 610.0
Y_COORDINATE = 1130.0

# Target Rarity and Characters
TARGET_RARITIES: List[str] = ["LEGENDARY"]
TARGET_CHARACTERS: List[str] = ["HERO", "DEF", "QUICK_SPEED"]

# Lock Coordinates for Expelling Hunter
FIRST_LOCK_X = 150.0
SECOND_LOCK_X = 325.0
THIRD_LOCK_X = 507.0
FOURTH_LOCK_X = 685.0
LOCK_Y = 1130.0

# Script Interval
LOOP_INTERVAL_SECONDS = 60 * 2

# Image Paths and OCR Thresholds
PER_SECOND_DAMAGE_IMAGE_PATH = "images/evil-hunter/perSecondDamage.png"
CHARACTER_OCR_PATH = "images/evil-hunter/character-ocr"
CHARACTER_THRESHOLD = 0.95
RARITY_OCR_PATH = "images/evil-hunter/rarity-ocr"
RARITY_THRESHOLD = 0.95

# OCR Region Coordinates
CHARACTER_REGION_X1 = 155
CHARACTER_REGION_Y1 = 118
CHARACTER_REGION_X2 = 560
CHARACTER_REGION_Y2 = 193

RARITY_REGION_X1 = 110
RARITY_REGION_Y1 = 670
RARITY_REGION_X2 = 335
RARITY_REGION_Y2 = 720

# Click Coordinates
TO_SOUL_SHOP_CLICK_X = 134
TO_SOUL_SHOP_CLICK_Y = 98
TO_HUNTER_BOX_CLICK_X = 350
TO_HUNTER_BOX_CLICK_Y = 1210
EXPEL_HUNTER_CLICK_X1 = 485
EXPEL_HUNTER_CLICK_Y1 = 935
EXPEL_HUNTER_CLICK_X2 = 333
EXPEL_HUNTER_CLICK_Y2 = 942
EXPEL_HUNTER_CLICK_X3 = 250
EXPEL_HUNTER_CLICK_Y3 = 750
EXPEL_HUNTER_CLICK_X4 = 406
EXPEL_HUNTER_CLICK_Y4 = 695


